### ISSUE TITLE
feedback from slack

### ISSUE THREAD

**Issue by jwchau** [alexdeeguz/WatchuWant#102]
1.  ~~Suggestion: description of app under headline (done)~~

2. ~~bug: login / signup buttons disappear when error is rendered (done)~~

3. ~~bug: price range buttons are squished on first login <try is working on the form(done)~~

4. ~~Suggestion: maybe give options for food cravings instead of one example (done)~~

5. ~~UX issue: not sure what the difference between eat here versus choose from visited option is(done)~~

6. ~~Bug: not sure if it’s intended but logging out from team page doesn’t redirect (done)~~

7. ~~Suggestion: the main page pictures transition way too fast LOL omg (done)~~

8. ~~Bug: anything over 24 mile search radius returns a failure~~

**Comment by jwchau** [comment]
6. bug is fixed.

**Comment by kendraodru** [comment]
I'll fix one and then work on 2

**Comment by alexdeeguz** [comment]
working on 8

**Comment by alexdeeguz** [comment]
8 fixed
