### ISSUE TITLE
site navigation

### ISSUE THREAD

**Issue by jwchau** [alexdeeguz/WatchuWant#90]
A bit more navigation would go a long way.

Link from \<Preferences> to \<UserShow>
Link from \<UserShow> to \<Preferences>
- Scenario: the user doesn't want to search, or if they do want to search again.

Link from \<RestaurantPage> to \<UserShow>
- Scenario: user doesn't want to click "Eat Here" or "Pick Another" buttons

Link from \<RestaurantPage> to \<Preferences>
- Scenario: user wants to edit their preferences, or they messed up a selection

**Comment by kendraodru** [comment]
Hmm hmm! Good point. I'll work on putting some links in the Nav bar.
